CoreWithADO/Models/ConnectionStr.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreWithADO.Models
{
    public class ConnectionStr
    {
        public static string Connection {get;set;}
    }
}

CoreWithADO/Models/Employees.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreWithADO.Models
{
    public class Employees
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string salary { get; set; }
        public string mobile { get; set; }
        public string gender { get; set; }

    }
}

CoreWithADO/Models/ErrorViewModel.cs
using System;

namespace CoreWithADO.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreWithADO/Models/UserSignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreWithADO.Models
{
    public class UserSignUp
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "User Name")]
        public string name { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email Address")]
        public string email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Passwrod")]
        public string password { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Confirm password not matched !")]
        [Display(Name = "Confirm Passwrod")]
        public string confirmpassword { get; set; }

        [Display(Name = "Mobile Number")]
        public string mobile { get; set; }

        [Display(Name = "Gender")]

        public string gender { get; set; }
        public string profile { get; set; }

    }

    public class UserSignIn
    {
        [Required]
        [EmailAddress]
        [Display(Name ="Email Address")]
        public string email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Passwrod")]
        public string password { get; set; }

        [Display(Name ="Remember me ?")]
        public bool isremember { get; set; }

    }

}

CoreWithADO/Controllers/AccountController.cs
using CoreWithADO.DataAccess;
using CoreWithADO.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CoreWithADO.Controllers
{
    public class AccountController : Controller
    {
        DBUserAuth dBUser = new DBUserAuth();

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost] 
        public async Task<IActionResult> Login(UserSignIn user)
        {
            if (ModelState.IsValid)
            {
                var result = dBUser.LoginUser(user);
                if (result)
                {
                    var claims = new List<Claim>() {
                    new Claim(ClaimTypes.NameIdentifier, Convert.ToString(user.email)),
                        new Claim(ClaimTypes.Name, user.password),

                };
                    //Initialize a new instance of the ClaimsIdentity with the claims and authentication scheme    
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    //Initialize a new instance of the ClaimsPrincipal with ClaimsIdentity    
                    var principal = new ClaimsPrincipal(identity);
                    //SignInAsync is a Extension method for Sign in a principal for the specified scheme.    
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties());


                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid email or password !");
                }
            }
            return View(user);
        }

        public IActionResult Register()
        {

            return View();
        }
        
        [HttpPost]
        public IActionResult Register(UserSignUp user)
        {
            if (ModelState.IsValid)
            {
                var result = dBUser.RegisterUser(user);
                if(result)
                {
                    ViewBag.success = "User registered successfully !";
                }
                else
                {
                    ModelState.AddModelError("Email", "Email already exist !");
                }
            }

            return View(user);
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }

   
}

CoreWithADO/Controllers/EmplooyeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreWithADO.DataAccess;
using CoreWithADO.Models;
using Microsoft.AspNetCore.Authorization;

namespace CoreWithADO.Controllers
{
    [Authorize]
    public class EmplooyeeController : Controller
    {
        EmployeeAccessDb db = new EmployeeAccessDb();

        public IActionResult Index()
        {
            var emps = db.GetEmployees();
            return View(emps);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employees emp)
        {
            db.CreateEmployee(emp);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var data = db.GetEmployee(id);
            return View(data);
        }
        
        [HttpPost]
        public IActionResult Update(Employees emp)
        {
            db.UpdateEmployee(emp);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
           db.DeleteEmployee(id);
            return RedirectToAction("Index");
        }

    }
}

CoreWithADO/Controllers/HomeController.cs
using CoreWithADO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CoreWithADO.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreWithADO/Views/Emplooyee/Create.cshtml
@model CoreWithADO.Models.Employees

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employees</h4>
<hr />
<div class="row">
    <div class="col-md-6 offset-2">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="fname" class="control-label"></label>
                <input asp-for="fname" class="form-control" />
                <span asp-validation-for="fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lname" class="control-label"></label>
                <input asp-for="lname" class="form-control" />
                <span asp-validation-for="lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobile" class="control-label"></label>
                <input asp-for="mobile" class="form-control" />
                <span asp-validation-for="mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreWithADO/Views/Emplooyee/Index.cshtml
@model IEnumerable<CoreWithADO.Models.Employees>
@{
}
<a asp-action="Create" asp-controller="Emplooyee"  class="btn btn-info">Create New Employee</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Fname</th>
            <th>Lname</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Salary</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var em in Model)
            {
                <tr>
                    <td>@em.id</td>
                    <td>@em.fname</td>
                    <td>@em.lname</td>
                    <td>@em.email</td>
                    <td>@em.mobile</td>
                    <td>@em.salary</td>
                    <td>@em.gender</td>
                    <td>
                        <a asp-action="Update" asp-controller="Emplooyee" asp-route-id="@em.id" class="btn btn-info">Edit</a>||
                        <a asp-action="Delete" asp-controller="Emplooyee" asp-route-id="@em.id" class="btn btn-info">Delete</a>

                    </td>
                </tr>
            }
    </tbody>
</table>

CoreWithADO/Views/Emplooyee/Update.cshtml
@model CoreWithADO.Models.Employees

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Employees</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                
                <input asp-for="id" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="fname" class="control-label"></label>
                <input asp-for="fname" class="form-control" />
                <span asp-validation-for="fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lname" class="control-label"></label>
                <input asp-for="lname" class="form-control" />
                <span asp-validation-for="lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobile" class="control-label"></label>
                <input asp-for="mobile" class="form-control" />
                <span asp-validation-for="mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreWithADO/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreWithADO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreWithADO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreWithADO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emplooyee" asp-action="Index">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-sm btn-info" asp-area="" asp-controller="Account" asp-action="Register">Register new User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-warning btn-sm ml-1"  asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CoreWithADO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>